//Verilog block level netlist file for netlist_amp
//Generated by UMN for ALIGN project 


module SCM_CMBANK_4 ( D1, D2, D3, D4, GND ); 
Switch_NMOS_10_1x1 MT0 ( .D3(D3), .D1(D1), .GND(GND), .GND(GND) ); 
Switch_NMOS_10_1x1 MT1 ( .D2(D2), .D1(D1), .GND(GND), .GND(GND) );
Switch_NMOS_10_1x1 MT2 ( .D1(D1), .D1(D1), .GND(GND), .GND(GND) );
Switch_NMOS_10_1x1 MT3 ( .D4(D4), .D1(D1), .GND(GND), .GND(GND) );
endmodule

module netlist_amp ( op, gnda, im, on, vdda1p2, ib, ip, om ); 
inout op, gnda, im, on, vdda1p2, ib, ip, om;

inv_1x I17 ( .on(gnda), .onb(on), .gnda(onb), .vdda1p2(vdda1p2) ); 
Switch_NMOS_10_1x1 MT24 ( .D(vdda1p2), .G(o1m), .S(om) ); 
Switch_NMOS_10_1x1 MT27 ( .D(vdda1p2), .G(o1p), .S(op) ); 
Switch_PMOS_10_1x1 MT30 ( .D(ib), .G(onb), .S(vbn) ); 
Switch_NMOS_10_1x1 MT31 ( .D(gnda), .G(vbn), .S(gnda) ); 
Switch_NMOS_10_1x1 MT54 ( .D(gnda), .G(onb), .S(vbn) ); 
res RR0 ( .net49(net49), .o1p(o1p) ); 
res RR1 ( .o1m(net49), .net49(o1m) ); 
SCM_CMBANK_4 MT26_MT0_MT20_MT25 ( .D1(vbn), .D3(op), .GND(gnda), .D2(net47), .D4(om) ); 
CMC_PMOS_10_1x4 MT3_MT4 ( .D1(o1m), .G(net49), .D2(o1p), .S(vdda1p2) ); 
DP_NMOS_75_3x10 MT2_MT1 ( .D1(o1m), .G1(ip), .S(net47), .D2(o1p), .G2(im) ); 

endmodule

module inv_1x ( IN, OUT, vm, vp ); 
inout IN, OUT, vm, vp;

Switch_PMOS_10_1x1 MT1 ( .D(OUT), .G(IN), .S(vp) ); 
Switch_NMOS_10_1x1 MT2 ( .D(OUT), .G(IN), .S(vm) ); 

endmodule


// End HDL models
// Global nets module
`celldefine
module cds_globals;

supply0 VDD;
supply1 VSS;

endmodule
`endcelldefine
